### ISSUE TITLE
cmake compilation crash - Linux ARM

### ISSUE THREAD

**Issue by Amotrax** [BlitterStudio/amiberry#1625]
Hello. Before I explain my problem to you with CMAKE I would like to congratulate you for this emulator because I’m a fan of Amiga since 1989 and I have always admired programmers, because I am disabled in this area because of my dyslexia.
I can't compile your projects with cmake but with make yes.
I use a Raspberry 4B+ with Rasbian version 10 or 11.
I make the compilations on this machine.
I can recompile the versions of the SDL2 with the right options for KMSDRM.
And I have a good benchmark with KMSDRM with the SDL2 recompiled for KMSDRM with : make -j4 PLATFORM=rpi4-sdl2. For versions 5.7.1 to 5.7.4.

But for the versions of Amberry Lite and Amiberry 7.x.x you deleted the makefile and therefore Make to impose Cmake. But Cmake never works with me or even since version 5.7.1. It systematically crash, indicates that there are errors.
I post the logs of errors below for version 5.7.1 and 5.7.4 and lite 5.8.0.
Thank you for your help, best regards.
Amotrax.

-------------------------------------------------------------------------------

LOG [ amiberry-5.7.1]

/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:121:17: error: conflicting declaration ‘typedef uae_u64 uintptr’
  121 | typedef uae_u64 uintptr;
      |                 ^~~~~~~
In file included from /home/pi/temp/amiberry-5.7.1/src/include/newcpu.h:80,
                 from /home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:31:
/home/pi/temp/amiberry-5.7.1/src/jit/compemu.h:43:17: note: previous declaration as ‘typedef uae_u32 uintptr’
   43 | typedef uae_u32 uintptr;
      |                 ^~~~~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp: In function ‘int handle_exception(mcontext_t*, long int)’:
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:131:38: error: ‘struct mcontext_t’ has no member named ‘pc’
  131 |  uintptr fault_pc = uintptr(sigcont->pc);
      |                                      ^~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:173:13: error: ‘struct mcontext_t’ has no member named ‘pc’
  173 |    sigcont->pc += 4;
      |             ^~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:185:13: error: ‘struct mcontext_t’ has no member named ‘pc’
  185 |    sigcont->pc += 4;
      |             ^~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:256:31: error: ‘struct mcontext_t’ has no member named ‘regs’
  256 |     uae_u32 oldval = sigcont->regs[rd];
      |                               ^~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:263:15: error: ‘struct mcontext_t’ has no member named ‘regs’
  263 |      sigcont->regs[rd] = (uae_u8)get_byte(amiga_addr);
      |               ^~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:271:15: error: ‘struct mcontext_t’ has no member named ‘regs’
  271 |      sigcont->regs[rd] = bswap_16((uae_u16)get_word(amiga_addr));
      |               ^~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:279:15: error: ‘struct mcontext_t’ has no member named ‘regs’
  279 |      sigcont->regs[rd] = bswap_32(get_long(amiga_addr));
      |               ^~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:286:79: error: ‘struct mcontext_t’ has no member named ‘regs’
  286 | "New value in x%d: 0x%08llx (old: 0x%08x)\n"), rd, sigcont->regs[rd], oldval);
      |                                                             ^~~~

/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:296:36: error: ‘struct mcontext_t’ has no member named ‘regs’
  296 |      put_byte(amiga_addr, sigcont->regs[rd]);
      |                                    ^~~~
In file included from /home/pi/temp/amiberry-5.7.1/src/include/memory.h:63,
                 from /home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:30:
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:304:45: error: ‘struct mcontext_t’ has no member named ‘regs’
  304 |      put_word(amiga_addr, bswap_16(sigcont->regs[rd]));
      |                                             ^~~~
/home/pi/temp/amiberry-5.7.1/src/machdep/maccess.h:86:36: note: in definition of macro ‘bswap_16’
   86 | #define bswap_16(x) do_byteswap_16(x)
      |                                    ^
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:312:45: error: ‘struct mcontext_t’ has no member named ‘regs’
  312 |      put_long(amiga_addr, bswap_32(sigcont->regs[rd]));
      |                                             ^~~~
/home/pi/temp/amiberry-5.7.1/src/machdep/maccess.h:87:36: note: in definition of macro ‘bswap_32’
   87 | #define bswap_32(x) do_byteswap_32(x)
      |                                    ^
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:324:13: error: ‘struct mcontext_t’ has no member named ‘pc’
  324 |    sigcont->pc += 4;
      |             ^~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp: In function ‘void signal_segv(int, siginfo_t*, void*)’:
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:360:38: error: ‘struct mcontext_t’ has no member named ‘regs’
  360 |  unsigned long long* regs = context->regs;
      |                                      ^~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:386:68: error: ‘struct mcontext_t’ has no member named ‘regs’
  386 | tput_log(_T("x%02d  = 0x%016llx\n"), i, ucontext->uc_mcontext.regs[i]);
      |                                                               ^~~~

/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:391:61: error: ‘struct mcontext_t’ has no member named ‘sp’
  391 |   output_log(_T("SP  = 0x%016llx\n"), ucontext->uc_mcontext.sp);
      |                                                             ^~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:392:61: error: ‘struct mcontext_t’ has no member named ‘pc’
  392 |   output_log(_T("PC  = 0x%016llx\n"), ucontext->uc_mcontext.pc);
      |                                                             ^~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:394:65: error: ‘struct mcontext_t’ has no member named ‘pstate’
  394 |  output_log(_T("pstate  = 0x%016llx\n"), ucontext->uc_mcontext.pstate);
      |                                                                ^~~~~~

/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:395:48: error: ‘struct mcontext_t’ has no member named ‘regs’
  395 |   void* getaddr = (void*)ucontext->uc_mcontext.regs[30];
      |                                                ^~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp: In function ‘void signal_buserror(int, siginfo_t*, void*)’:
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:471:38: error: ‘struct mcontext_t’ has no member named ‘regs’
  471 |  unsigned long long* regs = context->regs;
      |                                      ^~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:488:67: error: ‘struct mcontext_t’ has no member named ‘regs’
  488 | tput_log(_T("x%02d  = 0x%016llx\n"), i, ucontext->uc_mcontext.regs[i]);
      |                                                               ^~~~

/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:489:60: error: ‘struct mcontext_t’ has no member named ‘sp’
  489 |  output_log(_T("SP  = 0x%016llx\n"), ucontext->uc_mcontext.sp);
      |                                                            ^~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:490:60: error: ‘struct mcontext_t’ has no member named ‘pc’
  490 |  output_log(_T("PC  = 0x%016llx\n"), ucontext->uc_mcontext.pc);
      |                                                            ^~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:492:64: error: ‘struct mcontext_t’ has no member named ‘pstate’
  492 |  output_log(_T("pstate  = 0x%016llx\n"), ucontext->uc_mcontext.pstate);
      |                                                                ^~~~~~
/home/pi/temp/amiberry-5.7.1/src/osdep/sigsegv_handler.cpp:494:47: error: ‘struct mcontext_t’ has no member named ‘regs’
  494 |  void* getaddr = (void*)ucontext->uc_mcontext.regs[30];
      |                                               ^~~~
gmake[2]: *** [CMakeFiles/amiberry.dir/build.make:2695 : CMakeFiles/amiberry.dir/src/osdep/sigsegv_handler.cpp.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:158 : CMakeFiles/amiberry.dir/all] Erreur 2
gmake: *** [Makefile:171 : all] Erreur 2

-------------------------------------------------------------------------------

LOG [ amiberry-5.7.4]

/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:121:17: error: conflicting declaration ‘typedef uae_u64 uintptr’
  121 | typedef uae_u64 uintptr;
      |                 ^~~~~~~
In file included from /home/pi/temp/amiberry-5.7.4/src/include/newcpu.h:80,
                 from /home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:31:
/home/pi/temp/amiberry-5.7.4/src/jit/compemu.h:43:17: note: previous declaration as ‘typedef uae_u32 uintptr’
   43 | typedef uae_u32 uintptr;
      |                 ^~~~~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp: In function ‘int handle_exception(mcontext_t*, long int)’:
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:131:38: error: ‘struct mcontext_t’ has no member named ‘pc’
  131 |  uintptr fault_pc = uintptr(sigcont->pc);
      |                                      ^~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:173:13: error: ‘struct mcontext_t’ has no member named ‘pc’
  173 |    sigcont->pc += 4;
      |             ^~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:185:13: error: ‘struct mcontext_t’ has no member named ‘pc’
  185 |    sigcont->pc += 4;
      |             ^~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:256:31: error: ‘struct mcontext_t’ has no member named ‘regs’
  256 |     uae_u32 oldval = sigcont->regs[rd];
      |                               ^~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:263:15: error: ‘struct mcontext_t’ has no member named ‘regs’
  263 |      sigcont->regs[rd] = (uae_u8)get_byte(amiga_addr);
      |               ^~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:271:15: error: ‘struct mcontext_t’ has no member named ‘regs’
  271 |      sigcont->regs[rd] = bswap_16((uae_u16)get_word(amiga_addr));
      |               ^~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:279:15: error: ‘struct mcontext_t’ has no member named ‘regs’
  279 |      sigcont->regs[rd] = bswap_32(get_long(amiga_addr));
      |               ^~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:286:79: error: ‘struct mcontext_t’ has no member named ‘regs’
  286 | "New value in x%d: 0x%08llx (old: 0x%08x)\n"), rd, sigcont->regs[rd], oldval);
      |                                                             ^~~~

/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:296:36: error: ‘struct mcontext_t’ has no member named ‘regs’
  296 |      put_byte(amiga_addr, sigcont->regs[rd]);
      |                                    ^~~~
In file included from /home/pi/temp/amiberry-5.7.4/src/include/memory.h:63,
                 from /home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:30:
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:304:45: error: ‘struct mcontext_t’ has no member named ‘regs’
  304 |      put_word(amiga_addr, bswap_16(sigcont->regs[rd]));
      |                                             ^~~~
/home/pi/temp/amiberry-5.7.4/src/machdep/maccess.h:86:36: note: in definition of macro ‘bswap_16’
   86 | #define bswap_16(x) do_byteswap_16(x)
      |                                    ^
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:312:45: error: ‘struct mcontext_t’ has no member named ‘regs’
  312 |      put_long(amiga_addr, bswap_32(sigcont->regs[rd]));
      |                                             ^~~~
/home/pi/temp/amiberry-5.7.4/src/machdep/maccess.h:87:36: note: in definition of macro ‘bswap_32’
   87 | #define bswap_32(x) do_byteswap_32(x)
      |                                    ^
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:324:13: error: ‘struct mcontext_t’ has no member named ‘pc’
  324 |    sigcont->pc += 4;
      |             ^~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp: In function ‘void signal_segv(int, siginfo_t*, void*)’:
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:360:38: error: ‘struct mcontext_t’ has no member named ‘regs’
  360 |  unsigned long long* regs = context->regs;
      |                                      ^~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:386:68: error: ‘struct mcontext_t’ has no member named ‘regs’
  386 | tput_log(_T("x%02d  = 0x%016llx\n"), i, ucontext->uc_mcontext.regs[i]);
      |                                                               ^~~~

/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:391:61: error: ‘struct mcontext_t’ has no member named ‘sp’
  391 |   output_log(_T("SP  = 0x%016llx\n"), ucontext->uc_mcontext.sp);
      |                                                             ^~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:392:61: error: ‘struct mcontext_t’ has no member named ‘pc’
  392 |   output_log(_T("PC  = 0x%016llx\n"), ucontext->uc_mcontext.pc);
      |                                                             ^~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:394:65: error: ‘struct mcontext_t’ has no member named ‘pstate’
  394 |  output_log(_T("pstate  = 0x%016llx\n"), ucontext->uc_mcontext.pstate);
      |                                                                ^~~~~~

/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:395:48: error: ‘struct mcontext_t’ has no member named ‘regs’
  395 |   void* getaddr = (void*)ucontext->uc_mcontext.regs[30];
      |                                                ^~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp: In function ‘void signal_buserror(int, siginfo_t*, void*)’:
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:471:38: error: ‘struct mcontext_t’ has no member named ‘regs’
  471 |  unsigned long long* regs = context->regs;
      |                                      ^~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:488:67: error: ‘struct mcontext_t’ has no member named ‘regs’
  488 | tput_log(_T("x%02d  = 0x%016llx\n"), i, ucontext->uc_mcontext.regs[i]);
      |                                                               ^~~~

/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:489:60: error: ‘struct mcontext_t’ has no member named ‘sp’
  489 |  output_log(_T("SP  = 0x%016llx\n"), ucontext->uc_mcontext.sp);
      |                                                            ^~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:490:60: error: ‘struct mcontext_t’ has no member named ‘pc’
  490 |  output_log(_T("PC  = 0x%016llx\n"), ucontext->uc_mcontext.pc);
      |                                                            ^~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:492:64: error: ‘struct mcontext_t’ has no member named ‘pstate’
  492 |  output_log(_T("pstate  = 0x%016llx\n"), ucontext->uc_mcontext.pstate);
      |                                                                ^~~~~~
/home/pi/temp/amiberry-5.7.4/src/osdep/sigsegv_handler.cpp:494:47: error: ‘struct mcontext_t’ has no member named ‘regs’
  494 |  void* getaddr = (void*)ucontext->uc_mcontext.regs[30];
      |                                               ^~~~
gmake[2]: *** [CMakeFiles/amiberry.dir/build.make:2721 : CMakeFiles/amiberry.dir/src/osdep/sigsegv_handler.cpp.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:179 : CMakeFiles/amiberry.dir/all] Erreur 2
gmake: *** [Makefile:171 : all] Erreur 2

-------------------------------------------------------------------------------

[ amiberry lite 5.8.0 ]

![Image](https://github.com/user-attachments/assets/ce4eb9e0-2d80-4f95-b67b-ef9e114fb23e)

In file included from /home/pi/temp/amiberry-lite-5.8.0/src/gfxutil.cpp:16:
/home/pi/temp/amiberry-lite-5.8.0/src/machdep/maccess.h: In function ‘void alloc_colors_picasso(int, int, int, int, int, int, int, uae_u32*)’:
/home/pi/temp/amiberry-lite-5.8.0/src/machdep/maccess.h:98:3: error: invalid 'asm': invalid operand for code 'w'
   98 |   __asm__ (
      |   ^~~~~~~
/home/pi/temp/amiberry-lite-5.8.0/src/machdep/maccess.h:98:3: error: invalid 'asm': invalid operand for code 'w'
/home/pi/temp/amiberry-lite-5.8.0/src/machdep/maccess.h:98:3: error: invalid 'asm': invalid operand for code 'w'
/home/pi/temp/amiberry-lite-5.8.0/src/machdep/maccess.h:98:3: error: invalid 'asm': invalid operand for code 'w'
{entrée standard}: Messages de l'assembleur:
{entrée standard}:315: Erreur: registre ARM attendu -- `rev16 ,'
{entrée standard}:316: Erreur: registre ARM attendu -- `uxth ,'
gmake[2]: *** [CMakeFiles/amiberry-lite.dir/build.make:732 : CMakeFiles/amiberry-lite.dir/src/gfxutil.cpp.o] Erreur 1
gmake[1]: *** [CMakeFiles/Makefile2:202 : CMakeFiles/amiberry-lite.dir/all] Erreur 2
gmake: *** [Makefile:171 : all] Erreur 2

**Comment by midwan** [comment]
Hi there, and thank you for the kind words :)

How are you trying to compile it, exactly? Did you follow the wiki here? -> https://github.com/BlitterStudio/amiberry/wiki/Compile-from-source

I hope you are aware that you don't _have_ to compile it from source, if you just want to run it. There are binary releases now, in .DEB format, that you can simply install in your system. These are provided in the Releases page of each version (normal or Lite).

If you still want to compile it anyway, it should work if you follow the steps I mentioned in the wiki article above. There are automated builds running on Github with every new commit I make, to ensure that nothing is broken and it always builds as expected, for both ARM32/ARM64 (for Lite) and the rest of the supported platforms (for the non-Lite version). The supported distro versions are included in the releases, so you should be able to run the one labeled "Debian bullseye" in your case (Debian 11).

I'd recommend Amiberry-Lite for the RPI4, if you want to have things running at full speed. And depending on your OS, you should choose the 32-bit or 64-bit version accordingly (if you use the DEB package). When compiling, it builds it for your system automatically.

**Comment by solskogen** [comment]
You're using a very old version of Raspberry Pi OS. I'd suggest you upgrade to Bookworm (v12) - there will be dragons with 10 and 11.

**Comment by Amotrax** [comment]
Thank you for your ultra fast answer, I am amazed.
I followed your tutorial for compilations when I started learning to do this. Everything is ok in terms of outbuildings of the packages.

I had fun making benchmarks with Sysinfo 4.4.
By recompiling under Debian 10 = Retropie 4.8.
This allowed me to learn Better Linux, test the different versions of GCC and Clang their performance, test the compilation of SDL2, etc. I made a whole table of benchmark.
There is no pack of Amiberry Lite pre-compiled for Debian 10 (Buster) so if I want to do it myself Cmake crash.

Amiberry precompiled for Debian 11, performance (MIPS Sysinfo 4.4) are poor. SDL2 2.0.14 must be recompiled to activate KMSDMR. I do this with versions above 2.0.18 or 2.0.20 or ++. When I can compile with make no problem everything works despite some compilation errors for versions 5.7.x.
The problem of the precompiled versions for Debian 10 is that it calls the SDL2.0.14 and it does not work because KMSDRM is not activated so I must redo all the compilation so that the links are to my SDL 2.0.20 or more.
Cmake makes me blocked to do this kind of thing.
I will try on my side to break the bonds of the SDL 2.0.14. I haven't done it right now. This is why being able to compile myself allows me to use the version of SDL2 that I want.
I would also test with Debian 12 where I believe the version of SDL2 no longer cause problem with KMSDRM. I don't want to use X11. KMSDRM is more efficient.
My project is to make an RPI4 for Amiga only as fast as possible.
I’m giving you my benchmark file I love to do this kind of thing.
Best regards.
Amotrax.

**Comment by Amotrax** [comment]
> You're using a very old version of Raspberry Pi OS. I'd suggest you upgrade to Bookworm (v12) - there will be dragons with 10 and 11.

Yes i will test V12 after with my benchmark test. For now Retropie V10 buster is the faster.

**Comment by midwan** [comment]
RetroPie is a bit of a special case. As you said, it still runs on Buster by default (from their image), which is now out of support.
However, you _can_ run it on Bookworm (Debian12), if you install it manually on top of an RPI-OS Lite installation. Indeed I have done just that, in order to test things with the RPI5 here.

The older versions you mentioned used Dispmanx, which on the RPI is faster than KMSDRM, at least on the older Debian versions. With the newer models and newer RPIOS versions, Dispmanx is no longer available, but the performance has been improved as well, so it's acceptable. That would probably be the difference you saw between the versions.

Also, in Debian12 the default compositor is no longer X11, but Wayland.

**Comment by midwan** [comment]
Also, you probably want to move this to https://github.com/BlitterStudio/amiberry-lite instead :)

**Comment by Amotrax** [comment]
Dispmanx was very fast it was a shame that it was abandoned.
I am a beginner on the Linux versions of the Raspberry so I discovered all its technical galleys between DispmanX, KMS, Fake KMS, X11, Wayland and its old version of SDL2 2.0.10 and 2.0.14 which did not activate KMS by default… It is far from being simple when we discover everything by yourself ... But I learned a lot of interesting things thanks to all its technical problems ...
I will then soon test Debian 12 who everything seems easier to install Amiberry and the version of SDL2 is much better.
Thanks. Amiga for Ever :-)

**Comment by Amotrax** [comment]
Sorry I don't know why I have close myself this post. I'm new here and all is in english and this is not my mother langage. Sorry for that.

**Comment by midwan** [comment]
I don't think this issue belongs here anyway - it's related to Amiberry-Lite after the split of the versions, which is the edition more suited to the RPI.

I'd recommend you open a new issue there, after testing with Debian12, _if_ you still have a problem.

**Comment by Amotrax** [comment]
Ok, I understand. I'm installing Debian 12 and I have a whole bunch of problems with this version that I didn't have with 10 and 11. I'll comment on this in a new post in the amiberry lite section (Linux wears me out, it's a really boring and complicated text-based system).
Have a nice day ! :-)
